### ISSUE TITLE
Wrong link for the paper?

### ISSUE THREAD

**Issue by lushl9301** [zhouchunpong/Simplifying-Graph-Convolutional-Networks#3]
Hi I notice that the paper title is SGC, but linked to GCN..

could you please confirm if this is the implementation for SGC in tensorflow?

Thanks,

**Comment by zhouchunpong** [comment]
Sorry for the late and Thanks you very much for your information！
I linked the wrong paper and this is the implementation for SGC by Keras based TensorFlow.

Best,
